proxyon2 function

diff --git a/shell/shellrc.d/function b/shell/shellrc.d/function
--- a/shell/shellrc.d/function
+++ b/shell/shellrc.d/function
@@ -140,6 +140,90 @@ function slientExe(){
 #     rm "${destFile}.bak"
 # }
 
+function currentNetworkService(){
+    if [ "$(uname)" != "Darwin" ];then
+        echo "Only support MacOS"
+        return 1
+    fi
+    while read -r line; do
+        sname=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $2}')
+        sdev=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $4}')
+        #echo "Current service: $sname, $sdev, $currentservice"
+        if [ -n "$sdev" ]; then
+            ifout="$(ifconfig "$sdev" 2>/dev/null)"
+            echo "$ifout" | grep 'status: active' > /dev/null 2>&1
+            rc="$?"
+            if [ "$rc" -eq 0 ]; then
+                currentservice="$sname"
+                currentdevice="$sdev"
+                currentmac=$(echo "$ifout" | awk '/ether/{print $2}')
+
+                # may have multiple active devices, so echo it here
+                echo "$currentservice, $currentdevice, $currentmac"
+            fi
+        fi
+    done <<< "$(networksetup -listnetworkserviceorder | grep 'Hardware Port')"
+
+    if [ -z "$currentservice" ]; then
+        # >&2 echo "Could not find current service"
+        return 1
+    fi
+}
+
+macproxy(){
+    echo "TODO"
+}
+
+proxyon2(){
+    local defaultProxy="http://localhost:6116"
+    local proxy=${1}
+    if [ -z "${proxy}" ];then
+        case $(uname) in
+            Darwin)
+                local networkService=`currentNetworkService`
+                if [ -n "$networkService" ];then
+                    local ns=$(echo $networkService | awk -F, '{print $1}')
+                    if [ -n "$ns" ];then
+                        local webproxy=$(networksetup -getwebproxy $ns)
+                        if echo $webproxy | grep ^Enabled | grep -q 'Yes';then
+                            host=`echo $webproxy | grep ^Server | perl -ne 'print $1 if /Server:\s*(.+)/'`
+                            port=`echo $webproxy | grep ^Port | perl -ne 'print $1 if /Port:\s*(.+)/'`
+                            proxy="http://$host:$port"
+                            # echo "proxy: $proxy"
+                        fi
+                    fi
+                fi
+                ;;
+            Linux)
+                ;;
+        esac
+    fi
+
+    if [ -z "${proxy}" ];then
+        proxy=${defaultProxy}
+    fi
+
+    echoExec "export http_proxy=$proxy"
+    echoExec "export https_proxy=$proxy"
+    echoExec "export ftp_proxy=$proxy"
+    echoExec "export all_proxy=$proxy"
+    echoExec "export HTTP_PROXY=$proxy"
+    echoExec "export HTTPS_PROXY=$proxy"
+    echoExec "export FTP_PROXY=$proxy"
+    echoExec "export ALL_PROXY=$proxy"
+
+    #set git proxy
+    if command -v git >/dev/null 2>&1;then
+        echoExec "git config --global http.proxy $proxy"
+        echoExec "git config --global https.proxy $proxy"
+    fi
+
+    if command -v npm >/dev/null 2>&1;then
+        echo "npm config set registry http://registry.npm.taobao.org"
+        npm config set registry http://registry.npm.taobao.org
+    fi
+}
+
 function proxyon_(){
     local defaultProxy="http://localhost:6116"
     local proxy=${1}
